make:
	g++ -std=c++17 circle.cpp circle.hpp main.cpp line.cpp line.hpp box.cpp box.hpp drawable.cpp drawable.hpp factory.hpp factory.cpp exeption.hpp -o game -lsfml-graphics -lsfml-window -lsfml-system -lstdc++
run:
	./game
clean:
	rm game
	rm -f *.o